services:
  oracle-db:
    image: container-registry.oracle.com/database/free:latest
    container_name: droplite-oracle-db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=dropliteDBPAss
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./db-scripts:/opt/oracle/scripts/startup
    healthcheck:
      test: [ "CMD", "/opt/oracle/checkDBStatus.sh" ]
      interval: 30s
      timeout: 10s
      retries: 5

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: droplite-springboot-app
    ports:
      - "8080:8080"
    depends_on:
      oracle-db:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10


volumes:
  oracle-data: