ALTER SESSION SET CONTAINER=FREEPDB1;

CREATE USER droplite IDENTIFIED BY dropliteUserPass
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED ON USERS;


GRANT CREATE SESSION TO droplite;
GRANT CREATE TABLE TO droplite;
GRANT CREATE VIEW TO droplite;